export * from './bank.service';
import { BankService } from './bank.service';
export * from './message-queue-worker.service';
import { MessageQueueWorkerService } from './message-queue-worker.service';
export * from './pension.service';
import { PensionService } from './pension.service';
export * from './pension-bank-branch.service';
import { PensionBankBranchService } from './pension-bank-branch.service';
export * from './pension-category-master.service';
import { PensionCategoryMasterService } from './pension-category-master.service';
export * from './pension-component.service';
import { PensionComponentService } from './pension-component.service';
export * from './pension-component-rate.service';
import { PensionComponentRateService } from './pension-component-rate.service';
export * from './pension-component-revision.service';
import { PensionComponentRevisionService } from './pension-component-revision.service';
export * from './pension-factory.service';
import { PensionFactoryService } from './pension-factory.service';
export * from './pension-first-bill.service';
import { PensionFirstBillService } from './pension-first-bill.service';
export * from './pension-manual-ppo-receipt.service';
import { PensionManualPPOReceiptService } from './pension-manual-ppo-receipt.service';
export * from './pension-ppo-details.service';
import { PensionPPODetailsService } from './pension-ppo-details.service';
export * from './pension-ppo-status.service';
import { PensionPPOStatusService } from './pension-ppo-status.service';
export * from './pension-regular-bill.service';
import { PensionRegularBillService } from './pension-regular-bill.service';
export const APIS = [BankService, MessageQueueWorkerService, PensionService, PensionBankBranchService, PensionCategoryMasterService, PensionComponentService, PensionComponentRateService, PensionComponentRevisionService, PensionFactoryService, PensionFirstBillService, PensionManualPPOReceiptService, PensionPPODetailsService, PensionPPOStatusService, PensionRegularBillService];
