/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient,
    HttpHeaders,
    HttpParams,
    HttpResponse,
    HttpEvent,
    HttpParameterCodec,
    HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { PensionStatusDTOJsonAPIResponse } from '../model/pension-status-dto-json-api-response';
// @ts-ignore
import { PensionStatusEntryDTO } from '../model/pension-status-entry-dto';
// @ts-ignore
import { PensionStatusEntryDTOJsonAPIResponse } from '../model/pension-status-entry-dto-json-api-response';
// @ts-ignore
import { PensionStatusFlag } from '../model/pension-status-flag';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
    providedIn: 'root',
})
export class PensionPPOStatusService extends BaseService {
    constructor(
        protected httpClient: HttpClient,
        @Optional() @Inject(BASE_PATH) basePath: string | string[],
        @Optional() configuration?: Configuration
    ) {
        super(basePath, configuration);
    }

    /**
     * @param ppoId
     * @param statusFlag
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clearPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<PensionStatusDTOJsonAPIResponse>;
    public clearPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<PensionStatusDTOJsonAPIResponse>>;
    public clearPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<PensionStatusDTOJsonAPIResponse>>;
    public clearPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (ppoId === null || ppoId === undefined) {
            throw new Error(
                'Required parameter ppoId was null or undefined when calling clearPpoStatusFlagByPpoId.'
            );
        }
        if (statusFlag === null || statusFlag === undefined) {
            throw new Error(
                'Required parameter statusFlag was null or undefined when calling clearPpoStatusFlagByPpoId.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/ppo/${this.configuration.encodeParam({ name: 'ppoId', value: ppoId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int32' })}/status/${this.configuration.encodeParam({ name: 'statusFlag', value: statusFlag, in: 'path', style: 'simple', explode: false, dataType: 'PensionStatusFlag', dataFormat: undefined })}`;
        return this.httpClient.request<PensionStatusDTOJsonAPIResponse>(
            'delete',
            `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param ppoId
     * @param statusFlag
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<PensionStatusDTOJsonAPIResponse>;
    public getPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<PensionStatusDTOJsonAPIResponse>>;
    public getPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<PensionStatusDTOJsonAPIResponse>>;
    public getPpoStatusFlagByPpoId(
        ppoId: number,
        statusFlag: PensionStatusFlag,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (ppoId === null || ppoId === undefined) {
            throw new Error(
                'Required parameter ppoId was null or undefined when calling getPpoStatusFlagByPpoId.'
            );
        }
        if (statusFlag === null || statusFlag === undefined) {
            throw new Error(
                'Required parameter statusFlag was null or undefined when calling getPpoStatusFlagByPpoId.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/ppo/${this.configuration.encodeParam({ name: 'ppoId', value: ppoId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int32' })}/status/${this.configuration.encodeParam({ name: 'statusFlag', value: statusFlag, in: 'path', style: 'simple', explode: false, dataType: 'PensionStatusFlag', dataFormat: undefined })}`;
        return this.httpClient.request<PensionStatusDTOJsonAPIResponse>(
            'get',
            `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param pensionStatusEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setPpoStatusFlag(
        pensionStatusEntryDTO?: PensionStatusEntryDTO,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<PensionStatusEntryDTOJsonAPIResponse>;
    public setPpoStatusFlag(
        pensionStatusEntryDTO?: PensionStatusEntryDTO,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<PensionStatusEntryDTOJsonAPIResponse>>;
    public setPpoStatusFlag(
        pensionStatusEntryDTO?: PensionStatusEntryDTO,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<PensionStatusEntryDTOJsonAPIResponse>>;
    public setPpoStatusFlag(
        pensionStatusEntryDTO?: PensionStatusEntryDTO,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json',
        ];
        const httpContentTypeSelected: string | undefined =
            this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Content-Type',
                httpContentTypeSelected
            );
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/ppo/status`;
        return this.httpClient.request<PensionStatusEntryDTOJsonAPIResponse>(
            'post',
            `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: pensionStatusEntryDTO,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }
}
