/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient,
    HttpHeaders,
    HttpParams,
    HttpResponse,
    HttpEvent,
    HttpParameterCodec,
    HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse } from '../model/list-all-ppo-receipts-response-dto-table-response-dto-json-api-response';
// @ts-ignore
import { ManualPpoReceiptEntryDTO } from '../model/manual-ppo-receipt-entry-dto';
// @ts-ignore
import { ManualPpoReceiptResponseDTOJsonAPIResponse } from '../model/manual-ppo-receipt-response-dto-json-api-response';
// @ts-ignore
import { ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse } from '../model/manual-ppo-receipt-response-dto-table-response-dto-json-api-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
    providedIn: 'root',
})
export class PensionManualPPOReceiptService extends BaseService {
    constructor(
        protected httpClient: HttpClient,
        @Optional() @Inject(BASE_PATH) basePath: string | string[],
        @Optional() configuration?: Configuration
    ) {
        super(basePath, configuration);
    }

    /**
     * @param manualPpoReceiptEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPpoReceipt(
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;
    public createPpoReceipt(
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public createPpoReceipt(
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public createPpoReceipt(
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json',
        ];
        const httpContentTypeSelected: string | undefined =
            this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Content-Type',
                httpContentTypeSelected
            );
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipt`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOJsonAPIResponse>(
            'post',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: manualPpoReceiptEntryDTO,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllUnusedPpoReceipts(
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse>;
    public getAllUnusedPpoReceipts(
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<
        HttpResponse<ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse>
    >;
    public getAllUnusedPpoReceipts(
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<
        HttpEvent<ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse>
    >;
    public getAllUnusedPpoReceipts(
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipts/unused`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse>(
            'get',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param receiptId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPpoReceiptById(
        receiptId: number,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;
    public getPpoReceiptById(
        receiptId: number,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public getPpoReceiptById(
        receiptId: number,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public getPpoReceiptById(
        receiptId: number,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (receiptId === null || receiptId === undefined) {
            throw new Error(
                'Required parameter receiptId was null or undefined when calling getPpoReceiptById.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipt/${this.configuration.encodeParam({ name: 'receiptId', value: receiptId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOJsonAPIResponse>(
            'get',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param treasuryReceiptNo
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;
    public getPpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public getPpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public getPpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (treasuryReceiptNo === null || treasuryReceiptNo === undefined) {
            throw new Error(
                'Required parameter treasuryReceiptNo was null or undefined when calling getPpoReceiptByTreasuryReceiptNo.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipt/trid/${this.configuration.encodeParam({ name: 'treasuryReceiptNo', value: treasuryReceiptNo, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOJsonAPIResponse>(
            'get',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPpoReceipts(
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse>;
    public getPpoReceipts(
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<
        HttpResponse<ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse>
    >;
    public getPpoReceipts(
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<
        HttpEvent<ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse>
    >;
    public getPpoReceipts(
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipts`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse>(
            'get',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param receiptId
     * @param manualPpoReceiptEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePpoReceipt(
        receiptId: number,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;
    public updatePpoReceipt(
        receiptId: number,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public updatePpoReceipt(
        receiptId: number,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public updatePpoReceipt(
        receiptId: number,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (receiptId === null || receiptId === undefined) {
            throw new Error(
                'Required parameter receiptId was null or undefined when calling updatePpoReceipt.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json',
        ];
        const httpContentTypeSelected: string | undefined =
            this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Content-Type',
                httpContentTypeSelected
            );
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipt/${this.configuration.encodeParam({ name: 'receiptId', value: receiptId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOJsonAPIResponse>(
            'put',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: manualPpoReceiptEntryDTO,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }

    /**
     * @param treasuryReceiptNo
     * @param manualPpoReceiptEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;
    public updatePpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpResponse<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public updatePpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<HttpEvent<ManualPpoReceiptResponseDTOJsonAPIResponse>>;
    public updatePpoReceiptByTreasuryReceiptNo(
        treasuryReceiptNo: string,
        manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {
            httpHeaderAccept?: 'application/json';
            context?: HttpContext;
        }
    ): Observable<any> {
        if (treasuryReceiptNo === null || treasuryReceiptNo === undefined) {
            throw new Error(
                'Required parameter treasuryReceiptNo was null or undefined when calling updatePpoReceiptByTreasuryReceiptNo.'
            );
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders(
            'Bearer',
            'Authorization',
            localVarHeaders
        );

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ??
            this.configuration.selectHeaderAccept(['application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Accept',
                localVarHttpHeaderAcceptSelected
            );
        }

        const localVarHttpContext: HttpContext =
            options?.context ?? new HttpContext();

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json',
        ];
        const httpContentTypeSelected: string | undefined =
            this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set(
                'Content-Type',
                httpContentTypeSelected
            );
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (
                this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
            ) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/manual-ppo-receipt/trid/${this.configuration.encodeParam({ name: 'treasuryReceiptNo', value: treasuryReceiptNo, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ManualPpoReceiptResponseDTOJsonAPIResponse>(
            'put',
            `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: manualPpoReceiptEntryDTO,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress,
            }
        );
    }
}
