/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountHeadResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    id?: number;
    majorHead?: string | null;
    submajorHead?: string | null;
    minorHead?: string | null;
    planStatus?: string | null;
    schemeHead?: string | null;
    detailHead?: string | null;
    subdetailHead?: string | null;
    votedCharged?: string | null;
}

