/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { AccountHeadListItemResponseDTOTableResponseDTO } from './account-head-list-item-response-dto-table-response-dto';

export interface AccountHeadListItemResponseDTOTableResponseDTOJsonAPIResponse {
    result?: AccountHeadListItemResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace AccountHeadListItemResponseDTOTableResponseDTOJsonAPIResponse {}
