/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIResponseStatus = 'Success' | 'Warning' | 'Error' | 'Info';

export const APIResponseStatus = {
    Success: 'Success' as APIResponseStatus,
    Warning: 'Warning' as APIResponseStatus,
    Error: 'Error' as APIResponseStatus,
    Info: 'Info' as APIResponseStatus
};

