/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const APIResponseStatus = {
    Success: 'Success',
    Warning: 'Warning',
    Error: 'Error',
    Info: 'Info',
} as const;
export type APIResponseStatus =
    (typeof APIResponseStatus)[keyof typeof APIResponseStatus];
