/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { BankListResponseDTO } from './bank-list-response-dto';


export interface BankListResponseDTOJsonAPIResponse { 
    result?: BankListResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace BankListResponseDTOJsonAPIResponse {
}


