/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BankResponseDTO {
    dataSource?: object | null;
    id?: number;
    bankName?: string | null;
}
