/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { BaseDTO } from './base-dto';

export interface BaseDTOJsonAPIResponse {
    result?: BaseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace BaseDTOJsonAPIResponse {}
