/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillResponseDTO } from './bill-response-dto';


export interface BillListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    bills?: Array<BillResponseDTO> | null;
    readonly billCount?: number;
    preparedBy?: string | null;
    preparedOn?: string;
}

