/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { BillListResponseDTO } from './bill-list-response-dto';


export interface BillListResponseDTOJsonAPIResponse { 
    result?: BillListResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace BillListResponseDTOJsonAPIResponse {
}


