/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { BranchDeatilsDTO } from './branch-deatils-dto';


export interface BranchDeatilsDTOJsonAPIResponse { 
    result?: BranchDeatilsDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace BranchDeatilsDTOJsonAPIResponse {
}


