/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankResponseDTO } from './bank-response-dto';


export interface BranchResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    id?: number;
    bankId?: number;
    bank?: BankResponseDTO;
    branchName?: string | null;
    branchAddress?: string | null;
    ifscCode?: string | null;
    micrCode?: string | null;
    city?: string | null;
    district?: string | null;
    state?: string | null;
    pincode?: string | null;
}

