/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { BranchListResponseDTO } from './branch-list-response-dto';


export interface BranchListResponseDTOJsonAPIResponse { 
    result?: BranchListResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace BranchListResponseDTOJsonAPIResponse {
}


