/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankResponseDTO } from './bank-response-dto';
import { BranchListItemResponseDTO } from './branch-list-item-response-dto';


export interface BranchListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    readonly branchCount?: number;
    bank?: BankResponseDTO;
    branches?: Array<BranchListItemResponseDTO> | null;
}

