/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchResponseDTO } from './branch-response-dto';


export interface BranchListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    readonly branchCount?: number;
    branches?: Array<BranchResponseDTO> | null;
}

