/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BranchDeatilsDTO { 
    bankName?: string | null;
    mircCode?: string | null;
    branchName?: string | null;
    branchAddress?: string | null;
}

