/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ByTransferHeadEntryDTO {
    byTransferType: string;
    accountHeadId: number;
    byTransferDescription: string;
    agBytransfer?: boolean;
}
