/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { ByTransferHeadResponseDTO } from './by-transfer-head-response-dto';

export interface ByTransferHeadResponseDTOJsonAPIResponse {
    result?: ByTransferHeadResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ByTransferHeadResponseDTOJsonAPIResponse {}
