/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ByTransferHeadResponseDTO } from './by-transfer-head-response-dto';
import { TableHeader } from './table-header';

export interface ByTransferHeadResponseDTOTableResponseDTO {
    dataSource?: object | null;
    headers?: Array<TableHeader> | null;
    data?: Array<ByTransferHeadResponseDTO> | null;
    readonly dataCount?: number;
}
