/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { ByTransferHeadResponseDTOTableResponseDTO } from './by-transfer-head-response-dto-table-response-dto';

export interface ByTransferHeadResponseDTOTableResponseDTOJsonAPIResponse {
    result?: ByTransferHeadResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ByTransferHeadResponseDTOTableResponseDTOJsonAPIResponse {}
