/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComponentRateEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    categoryId: number;
    breakupId: number;
    effectiveFromDate: string;
    rateAmount: number;
    rateType: string;
}

