/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { ComponentRateResponseDTO } from './component-rate-response-dto';


export interface ComponentRateResponseDTOJsonAPIResponse { 
    result?: ComponentRateResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ComponentRateResponseDTOJsonAPIResponse {
}


