/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnlyDTO } from './date-only-dto';
import { APIResponseStatus } from './api-response-status';


export interface DateOnlyDTOJsonAPIResponse { 
    result?: DateOnlyDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace DateOnlyDTOJsonAPIResponse {
}


