/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DropdownDTO } from './dropdown-dto';
import { APIResponseStatus } from './api-response-status';


export interface DropdownDTOIEnumerableAPIResponse { 
    result?: Array<DropdownDTO> | null;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace DropdownDTOIEnumerableAPIResponse {
}


