/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EPpoEFPEntryDTO {
    dataSource?: { [key: string]: any } | null;
    ropa?: number;
    efpAmount?: number;
    efpFromDate?: string;
    efpUpToDate?: string;
}
