/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { EPpoReceiptPpoIdResponseDTO } from './e-ppo-receipt-ppo-id-response-dto';

export interface EPpoReceiptPpoIdResponseDTOJsonAPIResponse {
    result?: EPpoReceiptPpoIdResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace EPpoReceiptPpoIdResponseDTOJsonAPIResponse {}
