/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EPpoReceiptResponseDTO {
    dataSource?: { [key: string]: any } | null;
    id?: number;
    pensionApplnNo?: string | null;
}
