/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileEntryDTO } from './file-entry-dto';
import { EPpoNomineeEntryDTO } from './e-ppo-nominee-entry-dto';
import { EPpoAmountEntryDTO } from './e-ppo-amount-entry-dto';

export interface EPpoReceiptEntryDTO {
    ppoNo: string;
    pensionApplnNo: string;
    treasuryCode: string;
    freshRevisionFlag: string;
    ppoTypeCode: string;
    issuingLetterNo: string;
    issuingLetterDate: string;
    penCatId: number;
    sanctionAuthority: string;
    sanctionNo: string;
    sanctionDate: string;
    provisionalPensionStatus: string;
    pensionerName: string;
    religion: string;
    pensionerAddress?: string | null;
    mobileNumber?: string | null;
    aadhaarNo?: string | null;
    dateOfBirth: string;
    dateOfRetirement: string;
    dateOfDeath?: string | null;
    qualifyingServiceGrossYears?: number | null;
    qualifyingServiceGrossMonths?: number | null;
    qualifyingServiceGrossDays?: number | null;
    employeeLastPay?: number | null;
    employeeLastPayNotional?: number | null;
    commutedPensionAmount?: number;
    eppoAmounts?: Array<EPpoAmountEntryDTO> | null;
    eppoNominees?: Array<EPpoNomineeEntryDTO> | null;
    photoFile?: FileEntryDTO;
    signatureFile?: FileEntryDTO;
    ePpoFile?: FileEntryDTO;
}
