/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EPpoReceiptDetailDTO } from './e-ppo-receipt-detail-dto';
import { APIResponseStatus } from './api-response-status';

export interface EPpoReceiptDetailDTOJsonAPIResponse {
    result?: EPpoReceiptDetailDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace EPpoReceiptDetailDTOJsonAPIResponse {}
