/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { EPpoReceiptWithdrawlResponseDTO } from './e-ppo-receipt-withdrawl-response-dto';

export interface EPpoReceiptWithdrawlResponseDTOJsonAPIResponse {
    result?: EPpoReceiptWithdrawlResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace EPpoReceiptWithdrawlResponseDTOJsonAPIResponse {}
