/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileEntryDTO } from './file-entry-dto';

export interface EPpoReceiptRevisionEntryDTO {
    ppoNo: string;
    pensionApplnNo: string;
    treasuryCode: string;
    ppoId?: number | null;
    issuingLetterNo?: string | null;
    issuingLetterDate?: string | null;
    freshRevisionFlag: string;
    ppoTypeCode: string;
    ppoSubType: string;
    penCatId: number;
    employeeLastPay?: number | null;
    employeeLastPayNotional?: number | null;
    commutedPensionAmount: number;
    eppoFileId?: number | null;
    ePpoFile?: FileEntryDTO;
}
