/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { EPpoReceiptDetailDTOTableResponseDTO } from './e-ppo-receipt-detail-dto-table-response-dto';

export interface EPpoReceiptDetailDTOTableResponseDTOJsonAPIResponse {
    result?: EPpoReceiptDetailDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace EPpoReceiptDetailDTOTableResponseDTOJsonAPIResponse {}
