/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EPpoReceiptResponseDTO } from './e-ppo-receipt-response-dto';
import { APIResponseStatus } from './api-response-status';


export interface EPpoReceiptResponseDTOJsonAPIResponse { 
    result?: EPpoReceiptResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace EPpoReceiptResponseDTOJsonAPIResponse {
}


