/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EPpoNFPEntryDTO {
    dataSource?: { [key: string]: any } | null;
    ropa?: number;
    nfpAmount?: number;
    nfpFromDate?: string;
    nfpUpToDate?: string;
}
