/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EPpoAmountEntryDTO {
    dataSource?: { [key: string]: any } | null;
    amountType: string;
    classificationId?: number | null;
    fromDate?: string | null;
    toDate?: string | null;
    amount?: number;
    consolidated?: boolean;
    categoryId?: number | null;
}
