/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EPpoReceiptDetailDTO } from './e-ppo-receipt-detail-dto';
import { TableHeader } from './table-header';

export interface EPpoReceiptDetailDTOTableResponseDTO {
    dataSource?: object | null;
    headers?: Array<TableHeader> | null;
    data?: Array<EPpoReceiptDetailDTO> | null;
    readonly dataCount?: number;
}
