/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const FactoryEntityEnum = {
    ComponentRateEntryDto: 'ComponentRateEntryDTO',
    ManualPpoReceiptEntryDto: 'ManualPpoReceiptEntryDTO',
    PensionerEntryDto: 'PensionerEntryDTO',
    PpoSanctionDetailsEntryDto: 'PpoSanctionDetailsEntryDTO',
    PensionPrimaryCategoryEntryDto: 'PensionPrimaryCategoryEntryDTO',
    PensionSubCategoryEntryDto: 'PensionSubCategoryEntryDTO',
    PensionBreakupEntryDto: 'PensionBreakupEntryDTO',
    NomineeEntryDto: 'NomineeEntryDTO',
} as const;
export type FactoryEntityEnum =
    (typeof FactoryEntityEnum)[keyof typeof FactoryEntityEnum];
