/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FactoryEntityEnum = 'ComponentRateEntryDTO' | 'ManualPpoReceiptEntryDTO' | 'PensionerEntryDTO' | 'PpoSanctionDetailsEntryDTO' | 'PensionPrimaryCategoryEntryDTO' | 'PensionSubCategoryEntryDTO' | 'PensionBreakupEntryDTO';

export const FactoryEntityEnum = {
    ComponentRateEntryDto: 'ComponentRateEntryDTO' as FactoryEntityEnum,
    ManualPpoReceiptEntryDto: 'ManualPpoReceiptEntryDTO' as FactoryEntityEnum,
    PensionerEntryDto: 'PensionerEntryDTO' as FactoryEntityEnum,
    PpoSanctionDetailsEntryDto: 'PpoSanctionDetailsEntryDTO' as FactoryEntityEnum,
    PensionPrimaryCategoryEntryDto: 'PensionPrimaryCategoryEntryDTO' as FactoryEntityEnum,
    PensionSubCategoryEntryDto: 'PensionSubCategoryEntryDTO' as FactoryEntityEnum,
    PensionBreakupEntryDto: 'PensionBreakupEntryDTO' as FactoryEntityEnum
};

