/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FileResponseDTO {
    dataSource?: { [key: string]: any } | null;
    fileName?: string | null;
    contents?: string | null;
    id?: number;
    filePath?: string | null;
    fileMimeType?: string | null;
}
