/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { FinancialYearResponseDTO } from './financial-year-response-dto';

export interface FinancialYearResponseDTOJsonAPIResponse {
    result?: FinancialYearResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace FinancialYearResponseDTOJsonAPIResponse {}
