/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PpoBillBreakupResponseDTO } from './ppo-bill-breakup-response-dto';
import { PpoPaymentListItemDTO } from './ppo-payment-list-item-dto';
import { PensionerListItemDTO } from './pensioner-list-item-dto';
import { PensionCategoryResponseDTO } from './pension-category-response-dto';
import { PpoComponentRevisionResponseDTO } from './ppo-component-revision-response-dto';


export interface InitiateFirstPensionBillResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoId: number;
    id?: number;
    billType?: string;
    pensionCategory?: PensionCategoryResponseDTO;
    pensionerPayments?: Array<PpoPaymentListItemDTO> | null;
    ppoBillBreakups?: Array<PpoBillBreakupResponseDTO> | null;
    ppoComponentRevisions?: Array<PpoComponentRevisionResponseDTO> | null;
    billGeneratedUptoDate?: string;
    toDate?: string;
    billDate?: string;
    treasuryVoucherNo?: string | null;
    treasuryVoucherId?: number;
    treasuryVoucherDate?: string;
    grossAmount?: number;
    netAmount?: number;
    preparedBy?: string | null;
    preparedOn?: string;
    readonly pensionerId?: number;
    pensioner?: PensionerListItemDTO;
}

