/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchResponseDTO } from './branch-response-dto';


export interface LifeCertificateResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    financialYear: number;
    ppoId: number;
    ppoNo: string;
    bankAcNo: string;
    ifscCode: string;
    accountHolderName: string;
    mobileNumber: string;
    certificateFlag?: boolean | null;
    branchId?: number | null;
    id?: number;
    branch?: BranchResponseDTO;
    readonly bankId?: number;
}

