/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LifeCertificateDetailsResponseDTO } from './life-certificate-details-response-dto';

export interface LifeCertificateListResponseDTO {
    dataSource?: object | null;
    readonly lifeCertificateCount?: number;
    lifeCertificates?: Array<LifeCertificateDetailsResponseDTO> | null;
}
