/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LifeCertificateDetailsResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    id?: number;
    ppoId?: number;
    ppoNo?: string | null;
    pensionerName?: string | null;
    bankAcNo?: string | null;
    mobileNumber?: string | null;
    digitalMode?: boolean;
    certificateSubmitted?: boolean;
}

