/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { LifeCertificateResponseDTOTableResponseDTO } from './life-certificate-response-dto-table-response-dto';

export interface LifeCertificateResponseDTOTableResponseDTOJsonAPIResponse {
    result?: LifeCertificateResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace LifeCertificateResponseDTOTableResponseDTOJsonAPIResponse {}
