/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { LifeCertificateResponseDTO } from './life-certificate-response-dto';

export interface LifeCertificateResponseDTOJsonAPIResponse {
    result?: LifeCertificateResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace LifeCertificateResponseDTOJsonAPIResponse {}
