/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { ListAllPpoReceiptsResponseDTOTableResponseDTO } from './list-all-ppo-receipts-response-dto-table-response-dto';


export interface ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse { 
    result?: ListAllPpoReceiptsResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ListAllPpoReceiptsResponseDTOTableResponseDTOJsonAPIResponse {
}


