/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableHeader } from './table-header';
import { ListAllPpoReceiptsResponseDTO } from './list-all-ppo-receipts-response-dto';


export interface ListAllPpoReceiptsResponseDTOTableResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    headers?: Array<TableHeader> | null;
    data?: Array<ListAllPpoReceiptsResponseDTO> | null;
    readonly dataCount?: number;
}

