/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterEnum } from './filter-enum';


export interface ListHeader { 
    name?: string | null;
    dataType?: string | null;
    fieldName?: string | null;
    filterField?: string | null;
    filterEnums?: Array<FilterEnum> | null;
    isSortable?: boolean;
    isFilterable?: boolean;
    objectTypeValueField?: string | null;
}

