/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManualPpoReceiptResponseDTO } from './manual-ppo-receipt-response-dto';
import { TableHeader } from './table-header';

export interface ManualPpoReceiptResponseDTOTableResponseDTO {
    dataSource?: { [key: string]: any } | null;
    headers?: Array<TableHeader> | null;
    data?: Array<ManualPpoReceiptResponseDTO> | null;
    readonly dataCount?: number;
}
