/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManualPpoReceiptResponseDTO } from './manual-ppo-receipt-response-dto';
import { APIResponseStatus } from './api-response-status';


export interface ManualPpoReceiptResponseDTOJsonAPIResponse { 
    result?: ManualPpoReceiptResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ManualPpoReceiptResponseDTOJsonAPIResponse {
}


