/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManualPpoReceiptEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoNo: string;
    pensionerName: string;
    dateOfCommencement: string;
    mobileNumber?: string | null;
    receiptDate: string;
    psaCode: string;
    ppoType: string;
}

