/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { ManualPpoReceiptResponseDTOTableResponseDTO } from './manual-ppo-receipt-response-dto-table-response-dto';


export interface ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse { 
    result?: ManualPpoReceiptResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace ManualPpoReceiptResponseDTOTableResponseDTOJsonAPIResponse {
}


