/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchResponseDTO } from './branch-response-dto';


export interface NomineeResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoId: number;
    serialNo: number;
    nomineeName: string;
    relation: string;
    dateOfBirth: string;
    dateOfDeath?: string;
    nomineeType?: string | null;
    nomineePriority?: number | null;
    nomineeShare?: number | null;
    familyPension?: boolean | null;
    refused?: boolean | null;
    nomineeActive?: boolean | null;
    handicapped?: boolean;
    identificationMark?: string | null;
    bankAcNo?: string | null;
    branchId?: number | null;
    id?: number;
    branch?: BranchResponseDTO;
    readonly bankId?: number;
}

