/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NomineeResponseDTO } from './nominee-response-dto';


export interface NomineeListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    readonly nomineeCount?: number;
    nominees?: Array<NomineeResponseDTO> | null;
}

