/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableHeader } from './table-header';
import { NomineeResponseDTO } from './nominee-response-dto';

export interface NomineeResponseDTOTableResponseDTO {
    dataSource?: { [key: string]: any } | null;
    headers?: Array<TableHeader> | null;
    data?: Array<NomineeResponseDTO> | null;
    readonly dataCount?: number;
}
