/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { NomineeResponseDTO } from './nominee-response-dto';

export interface NomineeResponseDTOJsonAPIResponse {
    result?: NomineeResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace NomineeResponseDTOJsonAPIResponse {}
