/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionStatusFlag } from './pension-status-flag';


export interface PensionStatusEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    statusFlag: PensionStatusFlag;
    statusWef: string;
    ppoId: number;
}
export namespace PensionStatusEntryDTO {
}


