/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PensionerListItemDTOTableResponseDTO } from './pensioner-list-item-dto-table-response-dto';


export interface PensionerListItemDTOTableResponseDTOJsonAPIResponse { 
    result?: PensionerListItemDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionerListItemDTOTableResponseDTOJsonAPIResponse {
}


