/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionStatusFlag } from './pension-status-flag';
import { PensionStatusReassonFlag } from './pension-status-reasson-flag';


export interface PensionStatusEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    statusFlag: PensionStatusFlag;
    reasonFlag?: PensionStatusReassonFlag;
    statusWef: string;
    statusUpto?: string;
    reasonRemark?: string | null;
    ppoId: number;
}
export namespace PensionStatusEntryDTO {
}


