/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PensionStatusFlag = 'PpoSuspended' | 'PpoRunning' | 'PpoApproved' | 'PpoBankAccountApproved' | 'FirstPensionBillApproved';

export const PensionStatusFlag = {
    PpoSuspended: 'PpoSuspended' as PensionStatusFlag,
    PpoRunning: 'PpoRunning' as PensionStatusFlag,
    PpoApproved: 'PpoApproved' as PensionStatusFlag,
    PpoBankAccountApproved: 'PpoBankAccountApproved' as PensionStatusFlag,
    FirstPensionBillApproved: 'FirstPensionBillApproved' as PensionStatusFlag
};

