/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManualPpoReceiptResponseDTO } from './manual-ppo-receipt-response-dto';
import { BranchResponseDTO } from './branch-response-dto';
import { PpoSanctionDetailsResponseDTO } from './ppo-sanction-details-response-dto';
import { PensionCategoryResponseDTO } from './pension-category-response-dto';


export interface PensionerResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoNo: string;
    ppoType: string;
    ppoSubType: string;
    categoryId: number;
    branchId: number;
    accountHolderName: string;
    payMode: string;
    bankAcNo: string;
    pensionerName: string;
    gender?: string | null;
    dateOfBirth: string;
    dateOfDeath?: string | null;
    mobileNumber?: string | null;
    emailId?: string | null;
    pensionerAddress?: string | null;
    identificationMark?: string | null;
    panNo?: string | null;
    aadhaarNo?: string | null;
    dateOfRetirement: string;
    dateOfCommencement: string;
    basicPensionAmount: number;
    commutedPensionAmount: number;
    commutedFromDate?: string | null;
    commutedUptoDate?: string | null;
    enhancePensionAmount: number;
    efpAmount?: number | null;
    efpWefDate?: string | null;
    efpUptoDate?: string | null;
    nfpAmount?: number | null;
    nfpWefDate?: string | null;
    notionalPensionAmount?: number | null;
    notionalWefDate?: string | null;
    gpfTpfNo?: string | null;
    healthScheme?: boolean | null;
    employedPensioner?: boolean | null;
    reEmployedPensioner?: boolean | null;
    doublePension?: boolean | null;
    adhocPension?: boolean | null;
    provisionalPension?: boolean | null;
    interimAllowance?: boolean | null;
    sharedPension?: boolean | null;
    remarks?: string | null;
    reducedPensionAmount: number;
    religion: string;
    id?: number;
    ppoId?: number;
    category?: PensionCategoryResponseDTO;
    receipt?: ManualPpoReceiptResponseDTO;
    branch?: BranchResponseDTO;
    ppoSanctionDetails?: Array<PpoSanctionDetailsResponseDTO> | null;
    readonly bankId?: number;
    pensionerStatus?: string | null;
    firstPensionGenerated?: boolean | null;
}

