/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PensionerBankAcEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    payMode: string;
    accountHolderName: string;
    bankAcNo: string;
    ifscCode: string;
    bankCode: number;
    branchCode: number;
}

