/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PensionSubCategoryResponseDTO } from './pension-sub-category-response-dto';

export interface PensionSubCategoryResponseDTOJsonAPIResponse {
    result?: PensionSubCategoryResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionSubCategoryResponseDTOJsonAPIResponse {}
