/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PensionSubCategoryEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    subCategoryName: string;
}

