/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PensionBreakupResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    componentName: string;
    componentType: string;
    reliefFlag: boolean;
    id?: number;
}

