/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountHeadResponseDTO } from './account-head-response-dto';

export interface PensionPrimaryCategoryResponseDTO {
    dataSource?: object | null;
    accountHeadId: number;
    primaryCategoryName: string;
    id?: number;
    readonly headDetails?: string | null;
    accountHead?: AccountHeadResponseDTO;
}
