/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PensionPrimaryCategoryResponseDTO } from './pension-primary-category-response-dto';


export interface PensionPrimaryCategoryResponseDTOJsonAPIResponse { 
    result?: PensionPrimaryCategoryResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionPrimaryCategoryResponseDTOJsonAPIResponse {
}


