/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PensionStatusReassonFlag =
    | 'Others'
    | 'LifeCertificateSubmitted'
    | 'LifeCertificateNotSubmitted'
    | 'Death';

export const PensionStatusReassonFlag = {
    Others: 'Others' as PensionStatusReassonFlag,

    LifeCertificateSubmitted:
        'LifeCertificateSubmitted' as PensionStatusReassonFlag,

    LifeCertificateNotSubmitted:
        'LifeCertificateNotSubmitted' as PensionStatusReassonFlag,

    Death: 'Death' as PensionStatusReassonFlag,
};
