/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionPrimaryCategoryResponseDTOTableResponseDTO } from './pension-primary-category-response-dto-table-response-dto';
import { APIResponseStatus } from './api-response-status';


export interface PensionPrimaryCategoryResponseDTOTableResponseDTOJsonAPIResponse { 
    result?: PensionPrimaryCategoryResponseDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionPrimaryCategoryResponseDTOTableResponseDTOJsonAPIResponse {
}


