/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PensionCategoryListDTOTableResponseDTO } from './pension-category-list-dto-table-response-dto';


export interface PensionCategoryListDTOTableResponseDTOJsonAPIResponse { 
    result?: PensionCategoryListDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionCategoryListDTOTableResponseDTOJsonAPIResponse {
}


