/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PensionerEntryDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoNo: string;
    ppoType: string;
    ppoSubType: string;
    categoryId: number;
    pensionerName: string;
    gender?: string | null;
    dateOfBirth: string;
    mobileNumber?: string | null;
    emailId?: string | null;
    pensionerAddress?: string | null;
    identificationMark?: string | null;
    panNo?: string | null;
    aadhaarNo?: string | null;
    dateOfRetirement: string;
    dateOfCommencement: string;
    basicPensionAmount: number;
    commutedPensionAmount: number;
    enhancePensionAmount: number;
    reducedPensionAmount: number;
    religion: string;
}

