/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableHeader } from './table-header';
import { PensionPrimaryCategoryResponseDTO } from './pension-primary-category-response-dto';


export interface PensionPrimaryCategoryResponseDTOTableResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    headers?: Array<TableHeader> | null;
    data?: Array<PensionPrimaryCategoryResponseDTO> | null;
    readonly dataCount?: number;
}

