/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PpoByTransferHeadResponseList } from './ppo-by-transfer-head-response-list';
import { TableHeader } from './table-header';

export interface PpoByTransferHeadResponseListTableResponseDTO {
    dataSource?: { [key: string]: any } | null;
    headers?: Array<TableHeader> | null;
    data?: Array<PpoByTransferHeadResponseList> | null;
    readonly dataCount?: number;
}
