/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionerListItemDTO } from './pensioner-list-item-dto';


export interface PpoListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoList?: Array<PensionerListItemDTO> | null;
    readonly ppoCount?: number;
}

