/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoByTransferAmountResponseListDTO {
    dataSource?: object | null;
    fromDate: string;
    toDate: string;
    bytransferHeadId: number;
    bytransferAmount: number;
    remarks?: string | null;
    id?: number;
    readonly ppoNo?: string | null;
    readonly pensionerName?: string | null;
}
