/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoBillEntryDTO {
    ppoId: number;
    month: number;
    year: number;
    toDate: string;
}
