/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionerResponseDTO } from './pensioner-response-dto';
import { PpoBillBreakupResponseDTO } from './ppo-bill-breakup-response-dto';


export interface PpoRegularBillDetailsDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoId?: number;
    ppoNo?: string | null;
    pensionerName?: string | null;
    bankAcNo?: string | null;
    readonly totalPayableAmount?: number;
    basicPensionAmount?: number;
    dearnessReliefAmount?: number;
    medicalReliefAmount?: number;
    commutedPensionAmount?: number;
    overdrawlAmount?: number;
    dpPensionAmount?: number;
    additionalPensionAmount?: number;
    arrearPensionAmount?: number;
    interimReliefAmount?: number;
    byTransferAmount?: number;
    ppoBillBreakups?: Array<PpoBillBreakupResponseDTO> | null;
    pensioner?: PensionerResponseDTO;
}

