/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoByTransferHeadResponseList {
    dataSource?: { [key: string]: any } | null;
    id?: number;
    ppoNo?: string | null;
    pensionerName?: string | null;
    fromDate?: string;
    toDate?: string;
    bytransferHeadId?: number;
    bytransferAmount?: number;
    remarks?: string | null;
}
