/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PpoPaymentListItemDTO { 
    dataSource?: { [key: string]: any; } | null;
    fromDate?: string;
    toDate?: string;
    basicPensionAmount?: number;
    baseAmount?: number;
    breakupId?: number;
    componentName?: string | null;
    componentType?: string;
    amountPerMonth?: number;
    rateId?: number;
    rateType?: string;
    rateAmount?: number;
    periodInMonths?: number;
    periodInDays?: number;
    dueAmount?: number;
    drawnAmount?: number;
    netAmount?: number;
}

