/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoSanctionDetailsEntryDTO {
    ppoId: number;
    pensionerId: number;
    employeeName: string;
    sanctionAuthority: string;
    sanctionNo: string;
    sanctionDate: string;
    employeeDob?: string | null;
    employeeGender?: string | null;
    employeeDateOfAppointment?: string | null;
    employeeOffice?: string | null;
    employeeDesignation?: string | null;
    employeeLastPay?: number | null;
    averageEmolument?: number | null;
    employeeHrmsId?: string | null;
    issuingAuthority?: string | null;
    issuingLetterNo?: string | null;
    issuingLetterDate?: string | null;
    qualifyingServiceGrossYears?: number | null;
    qualifyingServiceGrossMonths?: number | null;
    qualifyingServiceGrossDays?: number | null;
    qualifyingServiceNetYears?: number | null;
    qualifyingServiceNetMonths?: number | null;
    qualifyingServiceNetDays?: number | null;
}
