/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PpoBillResponseDTO } from './ppo-bill-response-dto';


export interface PpoBillResponseDTOJsonAPIResponse { 
    result?: PpoBillResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PpoBillResponseDTOJsonAPIResponse {
}


