/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PpoBillSaveResponseDTO } from './ppo-bill-save-response-dto';


export interface PpoBillSaveResponseDTOJsonAPIResponse { 
    result?: PpoBillSaveResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PpoBillSaveResponseDTOJsonAPIResponse {
}


