/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PpoByTransferHeadResponseDTO } from './ppo-by-transfer-head-response-dto';

export interface PpoByTransferHeadResponseDTOJsonAPIResponse {
    result?: PpoByTransferHeadResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PpoByTransferHeadResponseDTOJsonAPIResponse {}
