/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PpoByTransferHeadResponseListTableResponseDTO } from './ppo-by-transfer-head-response-list-table-response-dto';

export interface PpoByTransferHeadResponseListTableResponseDTOJsonAPIResponse {
    result?: PpoByTransferHeadResponseListTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PpoByTransferHeadResponseListTableResponseDTOJsonAPIResponse {}
