/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchResponseDTO } from './branch-response-dto';
import { PensionCategoryResponseDTO } from './pension-category-response-dto';


export interface PpoComponentRevisionPpoListItemDTO { 
    dataSource?: { [key: string]: any; } | null;
    ppoId?: number;
    ppoNo?: string | null;
    pensionerName?: string | null;
    categoryDescription?: string | null;
    bankBranchName?: string | null;
    category?: PensionCategoryResponseDTO;
    branch?: BranchResponseDTO;
}

