/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoBillBreakupEntryDTO {
    ppoId: number;
    fromDate: string;
    toDate: string;
    breakupAmount: number;
    dueAmount?: number;
    drawnAmount?: number;
    readonly netAmount?: number;
}
