/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { PpoComponentRevisionPpoListItemDTOTableResponseDTO } from './ppo-component-revision-ppo-list-item-dto-table-response-dto';


export interface PpoComponentRevisionPpoListItemDTOTableResponseDTOJsonAPIResponse { 
    result?: PpoComponentRevisionPpoListItemDTOTableResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PpoComponentRevisionPpoListItemDTOTableResponseDTOJsonAPIResponse {
}


