/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PpoBillSaveResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    id?: number;
    ppoId?: number;
    billDate?: string;
    billType?: string;
}

