/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableHeader } from './table-header';
import { PpoByTransferAmountResponseListDTO } from './ppo-by-transfer-amount-response-list-dto';

export interface PpoByTransferAmountResponseListDTOTableResponseDTO {
    dataSource?: object | null;
    headers?: Array<TableHeader> | null;
    data?: Array<PpoByTransferAmountResponseListDTO> | null;
    readonly dataCount?: number;
}
