/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PpoPaymentHistoryResponseDTO {
    dataSource?: object | null;
    componentId?: number;
    componentName?: string | null;
    breakupAmount?: number;
    fromDate?: string;
    toDate?: string;
}
