/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegularBillResponseDTO } from './regular-bill-response-dto';


export interface RegularBillListResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    readonly regularBillCount?: number;
    regularBills?: Array<RegularBillResponseDTO> | null;
}

