/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const SeederEnums = {
    DatabaseSeeder: 'DatabaseSeeder',
    AccountHeadSeeder: 'AccountHeadSeeder',
    BankSeeder: 'BankSeeder',
    BillSeeder: 'BillSeeder',
    BranchSeeder: 'BranchSeeder',
    BreakupSeeder: 'BreakupSeeder',
    CategorySeeder: 'CategorySeeder',
    ClassificationSeeder: 'ClassificationSeeder',
    ComponentRateSeeder: 'ComponentRateSeeder',
    EppoAmountSeeder: 'EppoAmountSeeder',
    EppoNomineeSeeder: 'EppoNomineeSeeder',
    EppoReceiptSeeder: 'EppoReceiptSeeder',
    EppoRevisionSeeder: 'EppoRevisionSeeder',
    FinancialYearSeeder: 'FinancialYearSeeder',
    LifeCertificateSeeder: 'LifeCertificateSeeder',
    NomineeSeeder: 'NomineeSeeder',
    PensionerSeeder: 'PensionerSeeder',
    PpoBillSeeder: 'PpoBillSeeder',
    PpoReceiptSeeder: 'PpoReceiptSeeder',
    PpoSanctionDetailsSeeder: 'PpoSanctionDetailsSeeder',
    PpoStatusFlagSeeder: 'PpoStatusFlagSeeder',
    PrimaryCategorySeeder: 'PrimaryCategorySeeder',
    SubCategorySeeder: 'SubCategorySeeder',
    TreasurySeeder: 'TreasurySeeder',
} as const;
export type SeederEnums = (typeof SeederEnums)[keyof typeof SeederEnums];
