/**
 * CTS-BE
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Seeders =
    | 'DatabaseSeeder'
    | 'AccountHeadSeeder'
    | 'BankSeeder'
    | 'BillSeeder'
    | 'BranchSeeder'
    | 'BreakupSeeder'
    | 'CategorySeeder'
    | 'ClassificationSeeder'
    | 'ComponentRateSeeder'
    | 'EppoAmountSeeder'
    | 'EppoNomineeSeeder'
    | 'EppoReceiptSeeder'
    | 'EppoRevisionSeeder'
    | 'FinancialYearSeeder'
    | 'LifeCertificateSeeder'
    | 'NomineeSeeder'
    | 'PensionerSeeder'
    | 'PpoBillSeeder'
    | 'PpoReceiptSeeder'
    | 'PpoSanctionDetailsSeeder'
    | 'PpoStatusFlagSeeder'
    | 'PrimaryCategorySeeder'
    | 'SubCategorySeeder'
    | 'TreasurySeeder';

export const Seeders = {
    DatabaseSeeder: 'DatabaseSeeder' as Seeders,
    AccountHeadSeeder: 'AccountHeadSeeder' as Seeders,
    BankSeeder: 'BankSeeder' as Seeders,
    BillSeeder: 'BillSeeder' as Seeders,
    BranchSeeder: 'BranchSeeder' as Seeders,
    BreakupSeeder: 'BreakupSeeder' as Seeders,
    CategorySeeder: 'CategorySeeder' as Seeders,
    ClassificationSeeder: 'ClassificationSeeder' as Seeders,
    ComponentRateSeeder: 'ComponentRateSeeder' as Seeders,
    EppoAmountSeeder: 'EppoAmountSeeder' as Seeders,
    EppoNomineeSeeder: 'EppoNomineeSeeder' as Seeders,
    EppoReceiptSeeder: 'EppoReceiptSeeder' as Seeders,
    EppoRevisionSeeder: 'EppoRevisionSeeder' as Seeders,
    FinancialYearSeeder: 'FinancialYearSeeder' as Seeders,
    LifeCertificateSeeder: 'LifeCertificateSeeder' as Seeders,
    NomineeSeeder: 'NomineeSeeder' as Seeders,
    PensionerSeeder: 'PensionerSeeder' as Seeders,
    PpoBillSeeder: 'PpoBillSeeder' as Seeders,
    PpoReceiptSeeder: 'PpoReceiptSeeder' as Seeders,
    PpoSanctionDetailsSeeder: 'PpoSanctionDetailsSeeder' as Seeders,
    PpoStatusFlagSeeder: 'PpoStatusFlagSeeder' as Seeders,
    PrimaryCategorySeeder: 'PrimaryCategorySeeder' as Seeders,
    SubCategorySeeder: 'SubCategorySeeder' as Seeders,
    TreasurySeeder: 'TreasurySeeder' as Seeders,
};
