/**
 * CTS-BE
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TableHeader { 
    dataSource?: { [key: string]: any; } | null;
    name?: string | null;
    fieldName?: string | null;
}

