name: Playwright Tests for Angular CI

on: [push, pull_request]

jobs:
  build:
    name: Build Angular 14 Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present

  test:
    name: Run Playwright Tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 api.docker.test" | sudo tee -a /etc/hosts
      - name: Clone & Setup BackendAPI
        run: |
          git clone https://github.com/abusalam/IFMS-CTS.git ~/ifms-cts
          cd ~/ifms-cts
          git submodule update --init --recursive
          cp .env.docker .env
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose build dotnet --build-arg HOST_UID=$UID
          docker-compose up -d dotnet
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cp .env.playwright .env
      - name: Install dependencies
        run: npm ci
      # - name: Start Angular 14 Frontend
      #   run: npm run start
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --reporter=list
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30